#!/usr/bin/env php
<?php

define('ROOT', __DIR__);

require ROOT . '/vendor/autoload.php';

use Framework\Core\MigrationRunner;
use Framework\Core\MigrationCreator;
use Framework\Core\SeederRunner;

$command = $argv[1] ?? null;
$name    = $argv[2] ?? null;

switch ($command) {

    case 'migrate':
        (new MigrationRunner())->run();
        break;

    case 'make:migration':
        if (!$name) {
            echo "Provide migration name\n";
            exit;
        }

        (new MigrationCreator())->create($name);
        break;

    case 'rollback':
        (new MigrationRunner())->rollback();
        break;

    case 'migrate:status':
        (new MigrationRunner())->status();
        break;

    case 'db:seed':
        if (!$name) {
            echo "Provide seeder name\n";
            exit;
        }

        (new SeederRunner())->run($name);
        break;

    default:
        echo "Available commands:\n";
        echo "php console migrate\n";
        echo "php console make:migration NAME\n";
        echo "php console rollback\n";
}