#!/usr/bin/env php
<?php

define('BASE_PATH', __DIR__);

require BASE_PATH.'/vendor/autoload.php';

$app = require BASE_PATH.'/bootstrap/app.php';

$kernel = new Framework\Console\ConsoleKernel();

$kernel->register(App\Console\Commands\MakeController::class);

$kernel->handle($argv);